:art: try different

diff --git a/web/Dockerfile b/web/Dockerfile
--- a/web/Dockerfile
+++ b/web/Dockerfile
@@ -1,68 +1,68 @@
-FROM node:20-alpine AS deps
+# syntax=docker.io/docker/dockerfile:1
+
+FROM node:18-alpine AS base
+
+# Install dependencies only when needed
+FROM base AS deps
 # Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
 RUN apk add --no-cache libc6-compat
-WORKDIR /app
-ENV NODE_OPTIONS="--max_old_space_size=8192"
-
-COPY package.json pnpm-lock.yaml ./
-COPY web/package.json web/pnpm-lock.yaml web/
-
-RUN \
-  if [ -f pnpm-lock.yaml ]; then yarn global add pnpm@10.0.0 && pnpm m i --frozen-lockfile;\
-  else echo "Lockfile not found." && exit 1; \
-  fi
-
-FROM node:20-alpine AS builder
-WORKDIR /app
-COPY --from=deps /app/node_modules ./node_modules
-COPY --from=deps /app/web/node_modules ./web/node_modules
-COPY . .
-
-ARG ARG_SANITY_DATASET
-ARG ARG_SANITY_API_READ_TOKEN
-ARG ARG_SANITY_PROJECT_ID
-
-ENV NEXT_PUBLIC_SANITY_DATASET ${ARG_SANITY_DATASET}
-ENV NEXT_PUBLIC_SANITY_PROJECT_ID ${ARG_SANITY_PROJECT_ID}
-ENV SANITY_API_READ_TOKEN ${ARG_SANITY_API_READ_TOKEN}
-
-# https://nextjs.org/telemetry
-ENV NEXT_TELEMETRY_DISABLED 1
-
-RUN cd web && yarn build
-
-# Production image, copy all the files and run next
-FROM node:20-alpine AS runner
 WORKDIR /app
 
 ENV NODE_ENV production
 
-ARG ARG_ENV
-ARG ARG_SANITY_DATASET
+# Install dependencies based on the preferred package manager
+COPY package.json package-lock.json* pnpm-lock.yaml* .npmrc* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
-ENV ENV ${ARG_ENV}
-ENV NEXT_PUBLIC_SANITY_DATASET ${ARG_SANITY_DATASET}
 
+# Rebuild the source code only when needed
+FROM base AS builder
+WORKDIR /app
+COPY --from=deps /app/node_modules ./node_modules
+COPY . .
 
-ENV PORT 3000
-ENV USER nextjs
-ENV UID 12345
-# https://nextjs.org/telemetry
-ENV NEXT_TELEMETRY_DISABLED 1
+# Next.js collects completely anonymous telemetry data about general usage.
+# Learn more here: https://nextjs.org/telemetry
+# Uncomment the following line in case you want to disable telemetry during the build.
+ENV NEXT_TELEMETRY_DISABLED=1
 
-RUN addgroup -S "$USER"
-RUN adduser -S --uid "$UID" "$USER"
-RUN apk add --no-cache tini
+RUN \
+  if [ -f yarn.lock ]; then yarn run build; \
+  elif [ -f package-lock.json ]; then npm run build; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
+# Production image, copy all the files and run next
+FROM base AS runner
+WORKDIR /app
+
+ENV NODE_ENV=production
+# Uncomment the following line in case you want to disable telemetry during runtime.
+ENV NEXT_TELEMETRY_DISABLED=1
+
+RUN addgroup --system --gid 1001 nodejs
+RUN adduser --system --uid 1001 nextjs
+
+COPY --from=builder /app/public ./public
+
+# Automatically leverage output traces to reduce image size
 # https://nextjs.org/docs/advanced-features/output-file-tracing
-COPY --from=builder --chown="$USER":"$USER" /app/web/.next/standalone .
-COPY --from=builder --chown="$USER":"$USER" /app/web/.next/static ./.next/static
+COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
+COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
 
-USER "$UID"
+USER nextjs
 
-EXPOSE "$PORT"
+EXPOSE 3000
 
-ENTRYPOINT ["/sbin/tini", "--"]
+ENV PORT=3000
 
+# server.js is created by next build from the standalone output
+# https://nextjs.org/docs/pages/api-reference/config/next-config-js/output
+ENV HOSTNAME="0.0.0.0"
 CMD ["node", "server.js"]
-
